Compile Django message files and don't add gettext to slug
Thermondo/heroku-buildpack-gettext pull request #3
Opened 2016-12-15 22:10 UTC by codingjoe

2016-12-16 06:03 UTC, syphar requested changes

2016-12-16 06:03 UTC, syphar commented on bin/compile
> +find $BUILD_DIR -name \*.po -execdir msgfmt django.po -o django.mo \;
@codingjoe IMHO this buildpack should only take care of getting gettext into the slug/cache, nothing else.

2016-12-16 06:03 UTC, syphar commented on bin/compile
> +PATH=$GETTEXT_CACHE/bin:$PATH
perhaps this should be a env/setting somewhere? 

I can imagine people using this buildpack and wanting to have the binaries

2016-12-16 06:03 UTC, syphar commented on bin/compile
> +PATH=$GETTEXT_CACHE/bin:$PATH
apart from that, it makes it backwards incompatible

2016-12-16 09:31 UTC, codingjoe commented
@syphar it's definitely backwards incompatible, in facts it's a very different idea. it's only for Django and it's not a gettext build pack, but a gettext compiler. I guess it makes more sense to create an entirely new build pack.

2017-04-24 14:46 UTC, syphar commented
@samifahed I do not believe this will give us enough savings

2017-04-24 15:29 UTC, closed without merging